In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/archive/Resume/Resume.csv')
print(df.shape)
df.head()

(2484, 4)

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
print(df.columns.tolist())
df[['Category', 'Resume_str']].head(3)

['ID', 'Resume_str', 'Resume_html', 'Category']

  Category                                         Resume_str
0       HR           HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1       HR           HR SPECIALIST, US HR OPERATIONS      ...
2       HR           HR DIRECTOR       Summary      Over 2...

In [4]:
print(df['Resume_str'].iloc[0][:1000])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss preve

In [5]:
import spacy
from spacy.matcher import PhraseMatcher
nlp = spacy.load("en_core_web_sm")

In [7]:
skills_list = [
     "Python", "Java", "SQL", "JavaScript", "React", "Node.js",
    "Machine Learning", "Data Analysis", "Project Management",
    "Customer Service", "Team Management", "Communication",
    "Leadership", "Excel", "Marketing", "Sales", "Accounting",
    "Nursing", "Teaching", "Design", "AWS", "Docker", "Git"
]
matcher = PhraseMatcher(nlp.vocab, attr='LOWER')
patterns = [nlp.make_doc(skill) for skill in skills_list]
matcher.add("SKILLS", patterns)

In [9]:
doc = nlp(df['Resume_str'].iloc[0])
matches = matcher(doc)
found_skills = set()
for match_id, start, end in matches:
    found_skills.add(doc[start:end].text.title())
print(found_skills)

{'Accounting', 'Leadership', 'Customer Service', 'Marketing', 'Team Management', 'Data Analysis', 'Design', 'Sales'}